title: AArch64 Laptops
author: 💻 with 🩶
description: >- # this YAML syntax means to ignore newlines until "baseurl:"
  Providing the GNU/Linux community with resources Arm laptops since
  2019!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aarch64-laptops

# Build settings
theme: minima
plugins:
    - jekyll-relative-links
    - jekyll-titles-from-headings

header_pages:
  - about.md

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
